/// @description Init
hsp = 0;
vsp = 0;
grv = 0.25;
walksp = 1.5;
currentwalksp = 0;
hdashsp = 2.5;
vdashsp = 2.5;
xdir = 0;
ydir = 0;
currentdashtime = 0;
dashtime = 0.1;
maxdashtime = 0.3;
canJump = true;
airborne = false;
canDash = true;
isDashing = false;
dashInit = false;